apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'user-service'
      static_configs:
      - targets: ['user-service:8000']
      metrics_path: '/metrics'
      scrape_interval: 5s

    - job_name: 'cart-service'
      static_configs:
      - targets: ['cart-service:8002']
      metrics_path: '/metrics'
      scrape_interval: 5s

    - job_name: 'inventory-service'
      static_configs:
      - targets: ['inventory-service:8001']
      metrics_path: '/metrics'
      scrape_interval: 5s

    - job_name: 'order-service'
      static_configs:
      - targets: ['order-service:8003']
      metrics_path: '/metrics'
      scrape_interval: 5s

    - job_name: 'cadvisor'
      static_configs:
      - targets: ['cadvisor:8080']
      scrape_interval: 5s
